baseurl = "https://jnjosh.com/"
title = "internet weblog"
theme = "internet-weblog-2"
pygmentsstyle = "emacs"
Paginate = 10

disableAliases = true
[pagination]
  disableAliases = true

[params]
  handle = "@jnjosh"
  description = "Internet weblog of Software (Mac, iOS, Web) Developer, Josh Johnson."
  mainSections = ["workshop", "studio"]
  migratedBefore = 2026-08-12
  [params.glass]
    postsURL = "https://glass.photo/api/v2/users/jnjosh/posts"
    profileURL = "https://glass.photo/jnjosh"
  [params.author]
    Handle = "jnjosh"
    FirstName = "Josh"
    LastName = "Johnson"
    Location = "Raleigh, NC"

[params.footer]
  greeting = "Hi, [I'm Josh](/about/)"
  bio = """
I'm an Engineering Manager at [Adobe](https://adobe.com), a [photographer](https://jnjosh.photography)
sharing photos on [Glass](https://glass.photo/jnjosh), and I
[watch a lot of movies](https://letterboxd.com/jnjosh/films/diary/).
See what else I'm [doing now](/now/).
"""
  followIntro = "Follow me on"
  colophon = "Made in Raleigh, NC"

  [[params.footer.social]]
    name = "Mastodon"
    url = "https://mastodon.social/@jnjosh"
    rel = "me"
  [[params.footer.social]]
    name = "Instagram"
    url = "https://instagram.com/jnjosh"
  [[params.footer.social]]
    name = "GitHub"
    url = "https://github.com/jnjosh"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
  [privacy.vimeo]
    enableDNT = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false

[outputs]
  home = ["HTML", "RSS", "REDIRECTS"]
